//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy_CTFAK_UI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Legacy_CTFAK_UI.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations.
        /// </summary>
        internal static string Animations {
            get {
                return ResourceManager.GetString("Animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdrop.
        /// </summary>
        internal static string Backdrop {
            get {
                return ResourceManager.GetString("Backdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color
        ///
        ///Lang.
        /// </summary>
        internal static string ColorLang {
            get {
                return ResourceManager.GetString("ColorLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSOLE.
        /// </summary>
        internal static string ConsoleCaps {
            get {
                return ResourceManager.GetString("ConsoleCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump.
        /// </summary>
        internal static string Dump {
            get {
                return ResourceManager.GetString("Dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump All.
        /// </summary>
        internal static string DumpAll {
            get {
                return ResourceManager.GetString("DumpAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Extensions.
        /// </summary>
        internal static string DumpExtensions {
            get {
                return ResourceManager.GetString("DumpExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Images.
        /// </summary>
        internal static string DumpImages {
            get {
                return ResourceManager.GetString("DumpImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump MFA.
        /// </summary>
        internal static string DumpMFA {
            get {
                return ResourceManager.GetString("DumpMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Music.
        /// </summary>
        internal static string DumpMusic {
            get {
                return ResourceManager.GetString("DumpMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Selected.
        /// </summary>
        internal static string DumpSelected {
            get {
                return ResourceManager.GetString("DumpSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Sorted Images.
        /// </summary>
        internal static string DumpSortedImages {
            get {
                return ResourceManager.GetString("DumpSortedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Sounds.
        /// </summary>
        internal static string DumpSounds {
            get {
                return ResourceManager.GetString("DumpSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using CTFAK you agree that you will only
        ///use the decompiled MFAs for personal use and
        ///educational purposes.
        ///
        ///You also agree that unless you are the
        ///original creator or have been given
        ///permission, you will not recompile any games.
        ///using this tool..
        /// </summary>
        internal static string DumpWarning {
            get {
                return ResourceManager.GetString("DumpWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string Frames {
            get {
                return ResourceManager.GetString("Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion application.
        /// </summary>
        internal static string FusionSelector {
            get {
                return ResourceManager.GetString("FusionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        internal static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chunks.
        /// </summary>
        internal static string LoadChunks {
            get {
                return ResourceManager.GetString("LoadChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader Data.
        /// </summary>
        internal static string LoaderData {
            get {
                return ResourceManager.GetString("LoaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frames.
        /// </summary>
        internal static string LoadFrames {
            get {
                return ResourceManager.GetString("LoadFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.
        /// </summary>
        internal static string LoadImages {
            get {
                return ResourceManager.GetString("LoadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sounds.
        /// </summary>
        internal static string LoadSounds {
            get {
                return ResourceManager.GetString("LoadSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA Dump.
        /// </summary>
        internal static string MFADump {
            get {
                return ResourceManager.GetString("MFADump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Items.
        /// </summary>
        internal static string NumberofItems {
            get {
                return ResourceManager.GetString("NumberofItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Frames.
        /// </summary>
        internal static string NumFrames {
            get {
                return ResourceManager.GetString("NumFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Images.
        /// </summary>
        internal static string NumImages {
            get {
                return ResourceManager.GetString("NumImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Music.
        /// </summary>
        internal static string NumMusic {
            get {
                return ResourceManager.GetString("NumMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Objects.
        /// </summary>
        internal static string NumObjects {
            get {
                return ResourceManager.GetString("NumObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Sounds.
        /// </summary>
        internal static string NumSounds {
            get {
                return ResourceManager.GetString("NumSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Dump Folder.
        /// </summary>
        internal static string OpenDumpFolder {
            get {
                return ResourceManager.GetString("OpenDumpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string OpenPlugin {
            get {
                return ResourceManager.GetString("OpenPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Data.
        /// </summary>
        internal static string PackData {
            get {
                return ResourceManager.GetString("PackData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO BE FILLED.
        /// </summary>
        internal static string PackDataInfo {
            get {
                return ResourceManager.GetString("PackDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraphs.
        /// </summary>
        internal static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Animation.
        /// </summary>
        internal static string PlayAnimation {
            get {
                return ResourceManager.GetString("PlayAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sound.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO BE FILLED.
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Version.
        /// </summary>
        internal static string ProductVer {
            get {
                return ResourceManager.GetString("ProductVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Backdrop.
        /// </summary>
        internal static string QuickBackdrop {
            get {
                return ResourceManager.GetString("QuickBackdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Events.
        /// </summary>
        internal static string RemoveEvents {
            get {
                return ResourceManager.GetString("RemoveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Images.
        /// </summary>
        internal static string RemoveImages {
            get {
                return ResourceManager.GetString("RemoveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Version.
        /// </summary>
        internal static string RuntimeVer {
            get {
                return ResourceManager.GetString("RuntimeVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game.
        /// </summary>
        internal static string SelectGame {
            get {
                return ResourceManager.GetString("SelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Object Icons.
        /// </summary>
        internal static string SetObjectIcons {
            get {
                return ResourceManager.GetString("SetObjectIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO BE FILLED.
        /// </summary>
        internal static string SoundInfo {
            get {
                return ResourceManager.GetString("SoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sound.
        /// </summary>
        internal static string StopSound {
            get {
                return ResourceManager.GetString("StopSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Chunks.
        /// </summary>
        internal static string TraceChunks {
            get {
                return ResourceManager.GetString("TraceChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
