//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy_CTFAK_UI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Legacy_CTFAK_UI.Languages.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актив.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анимация.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анимации.
        /// </summary>
        internal static string Animations {
            get {
                return ResourceManager.GetString("Animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бэкдроп.
        /// </summary>
        internal static string Backdrop {
            get {
                return ResourceManager.GetString("Backdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия CTF.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет
        ///
        ///Язык.
        /// </summary>
        internal static string ColorLang {
            get {
                return ResourceManager.GetString("ColorLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КОНСОЛЬ.
        /// </summary>
        internal static string ConsoleCaps {
            get {
                return ResourceManager.GetString("ConsoleCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирайт.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счётчик.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт.
        /// </summary>
        internal static string Dump {
            get {
                return ResourceManager.GetString("Dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт всего.
        /// </summary>
        internal static string DumpAll {
            get {
                return ResourceManager.GetString("DumpAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт расширений.
        /// </summary>
        internal static string DumpExtensions {
            get {
                return ResourceManager.GetString("DumpExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт изображений.
        /// </summary>
        internal static string DumpImages {
            get {
                return ResourceManager.GetString("DumpImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт MFA.
        /// </summary>
        internal static string DumpMFA {
            get {
                return ResourceManager.GetString("DumpMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт музыка.
        /// </summary>
        internal static string DumpMusic {
            get {
                return ResourceManager.GetString("DumpMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт выбранного.
        /// </summary>
        internal static string DumpSelected {
            get {
                return ResourceManager.GetString("DumpSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт с сортировкой.
        /// </summary>
        internal static string DumpSortedImages {
            get {
                return ResourceManager.GetString("DumpSortedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт звуков.
        /// </summary>
        internal static string DumpSounds {
            get {
                return ResourceManager.GetString("DumpSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используя CTFAK, вы соглашаетесь использоваться
        ///декомпилированные MFA файлы только в
        ///образовательных целях.
        ///
        ///Вы также соглашаетесь, что если вами не было
        ///получено разрешения от создателя игры, вы не
        ///будете перекомпилировать полученные MFA файлы.
        /// </summary>
        internal static string DumpWarning {
            get {
                return ResourceManager.GetString("DumpWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширения.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтры.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Флаг.
        /// </summary>
        internal static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сцена.
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сцены.
        /// </summary>
        internal static string Frames {
            get {
                return ResourceManager.GetString("Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение Fusion.
        /// </summary>
        internal static string FusionSelector {
            get {
                return ResourceManager.GetString("FusionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Библиотеки.
        /// </summary>
        internal static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чанки.
        /// </summary>
        internal static string LoadChunks {
            get {
                return ResourceManager.GetString("LoadChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные чанка.
        /// </summary>
        internal static string LoaderData {
            get {
                return ResourceManager.GetString("LoaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сцены.
        /// </summary>
        internal static string LoadFrames {
            get {
                return ResourceManager.GetString("LoadFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображения.
        /// </summary>
        internal static string LoadImages {
            get {
                return ResourceManager.GetString("LoadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звуки.
        /// </summary>
        internal static string LoadSounds {
            get {
                return ResourceManager.GetString("LoadSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основное.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт MFA.
        /// </summary>
        internal static string MFADump {
            get {
                return ResourceManager.GetString("MFADump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемещения.
        /// </summary>
        internal static string Movements {
            get {
                return ResourceManager.GetString("Movements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество элементов.
        /// </summary>
        internal static string NumberofItems {
            get {
                return ResourceManager.GetString("NumberofItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество сцен.
        /// </summary>
        internal static string NumFrames {
            get {
                return ResourceManager.GetString("NumFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество изображений.
        /// </summary>
        internal static string NumImages {
            get {
                return ResourceManager.GetString("NumImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество музыкальных файлов.
        /// </summary>
        internal static string NumMusic {
            get {
                return ResourceManager.GetString("NumMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество объектов.
        /// </summary>
        internal static string NumObjects {
            get {
                return ResourceManager.GetString("NumObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество звуков.
        /// </summary>
        internal static string NumSounds {
            get {
                return ResourceManager.GetString("NumSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка экспорта.
        /// </summary>
        internal static string OpenDumpFolder {
            get {
                return ResourceManager.GetString("OpenDumpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить.
        /// </summary>
        internal static string OpenPlugin {
            get {
                return ResourceManager.GetString("OpenPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доп. Файлы.
        /// </summary>
        internal static string PackData {
            get {
                return ResourceManager.GetString("PackData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТСУТСТВУЕТ.
        /// </summary>
        internal static string PackDataInfo {
            get {
                return ResourceManager.GetString("PackDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параграфы.
        /// </summary>
        internal static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проиграть анимацию.
        /// </summary>
        internal static string PlayAnimation {
            get {
                return ResourceManager.GetString("PlayAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проиграть звук.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТСУТСТВУЕТ.
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плагины.
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия продукта.
        /// </summary>
        internal static string ProductVer {
            get {
                return ResourceManager.GetString("ProductVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to быстрый бэкдроп.
        /// </summary>
        internal static string QuickBackdrop {
            get {
                return ResourceManager.GetString("QuickBackdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить события.
        /// </summary>
        internal static string RemoveEvents {
            get {
                return ResourceManager.GetString("RemoveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить изображения.
        /// </summary>
        internal static string RemoveImages {
            get {
                return ResourceManager.GetString("RemoveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия среды.
        /// </summary>
        internal static string RuntimeVer {
            get {
                return ResourceManager.GetString("RuntimeVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать файл.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать игру.
        /// </summary>
        internal static string SelectGame {
            get {
                return ResourceManager.GetString("SelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать иконки объектов.
        /// </summary>
        internal static string SetObjectIcons {
            get {
                return ResourceManager.GetString("SetObjectIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТСУТСТВУЕТ.
        /// </summary>
        internal static string SoundInfo {
            get {
                return ResourceManager.GetString("SoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звуки.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить звук.
        /// </summary>
        internal static string StopSound {
            get {
                return ResourceManager.GetString("StopSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трассировка чанков.
        /// </summary>
        internal static string TraceChunks {
            get {
                return ResourceManager.GetString("TraceChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
