//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy_CTFAK_UI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spanish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Legacy_CTFAK_UI.Languages.Spanish", typeof(Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animación.
        /// </summary>
        internal static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animaciones.
        /// </summary>
        internal static string Animations {
            get {
                return ResourceManager.GetString("Animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fondo.
        /// </summary>
        internal static string Backdrop {
            get {
                return ResourceManager.GetString("Backdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:
        ///
        ///Lenguaje:.
        /// </summary>
        internal static string ColorLang {
            get {
                return ResourceManager.GetString("ColorLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSOLA.
        /// </summary>
        internal static string ConsoleCaps {
            get {
                return ResourceManager.GetString("ConsoleCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derechos de autor.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contador.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump.
        /// </summary>
        internal static string Dump {
            get {
                return ResourceManager.GetString("Dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumpear Todo.
        /// </summary>
        internal static string DumpAll {
            get {
                return ResourceManager.GetString("DumpAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump de Extensiones.
        /// </summary>
        internal static string DumpExtensions {
            get {
                return ResourceManager.GetString("DumpExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump de Imágenes.
        /// </summary>
        internal static string DumpImages {
            get {
                return ResourceManager.GetString("DumpImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump del MFA.
        /// </summary>
        internal static string DumpMFA {
            get {
                return ResourceManager.GetString("DumpMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump de Musica.
        /// </summary>
        internal static string DumpMusic {
            get {
                return ResourceManager.GetString("DumpMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Seleccionado.
        /// </summary>
        internal static string DumpSelected {
            get {
                return ResourceManager.GetString("DumpSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump de Imágenes Ordenadas.
        /// </summary>
        internal static string DumpSortedImages {
            get {
                return ResourceManager.GetString("DumpSortedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump de Sonidos.
        /// </summary>
        internal static string DumpSounds {
            get {
                return ResourceManager.GetString("DumpSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using CTFAK you agree that you will only
        ///use the decompiled MFAs for personal use and
        ///educational purposes.
        ///
        ///You also agree that unless you are the
        ///original creator or have been given
        ///permission, you will not recompile any games.
        ///using this tool..
        /// </summary>
        internal static string DumpWarning {
            get {
                return ResourceManager.GetString("DumpWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensiones.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandera.
        /// </summary>
        internal static string Flag {
            get {
                return ResourceManager.GetString("Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco.
        /// </summary>
        internal static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcos.
        /// </summary>
        internal static string Frames {
            get {
                return ResourceManager.GetString("Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación de Fusión.
        /// </summary>
        internal static string FusionSelector {
            get {
                return ResourceManager.GetString("FusionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librerias.
        /// </summary>
        internal static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trozos.
        /// </summary>
        internal static string LoadChunks {
            get {
                return ResourceManager.GetString("LoadChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del cargador.
        /// </summary>
        internal static string LoaderData {
            get {
                return ResourceManager.GetString("LoaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marcos.
        /// </summary>
        internal static string LoadFrames {
            get {
                return ResourceManager.GetString("LoadFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imagenes.
        /// </summary>
        internal static string LoadImages {
            get {
                return ResourceManager.GetString("LoadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sonidos.
        /// </summary>
        internal static string LoadSounds {
            get {
                return ResourceManager.GetString("LoadSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump del MFA.
        /// </summary>
        internal static string MFADump {
            get {
                return ResourceManager.GetString("MFADump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Items.
        /// </summary>
        internal static string NumberofItems {
            get {
                return ResourceManager.GetString("NumberofItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Marcos.
        /// </summary>
        internal static string NumFrames {
            get {
                return ResourceManager.GetString("NumFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Imagenes.
        /// </summary>
        internal static string NumImages {
            get {
                return ResourceManager.GetString("NumImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Canciones.
        /// </summary>
        internal static string NumMusic {
            get {
                return ResourceManager.GetString("NumMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Objetos.
        /// </summary>
        internal static string NumObjects {
            get {
                return ResourceManager.GetString("NumObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Sonidos.
        /// </summary>
        internal static string NumSounds {
            get {
                return ResourceManager.GetString("NumSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetos.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir Carpeta del Dump.
        /// </summary>
        internal static string OpenDumpFolder {
            get {
                return ResourceManager.GetString("OpenDumpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutar.
        /// </summary>
        internal static string OpenPlugin {
            get {
                return ResourceManager.GetString("OpenPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empacar la información.
        /// </summary>
        internal static string PackData {
            get {
                return ResourceManager.GetString("PackData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA SER RELLENADO.
        /// </summary>
        internal static string PackDataInfo {
            get {
                return ResourceManager.GetString("PackDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Párrafos.
        /// </summary>
        internal static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproducir animación.
        /// </summary>
        internal static string PlayAnimation {
            get {
                return ResourceManager.GetString("PlayAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproducir sonido.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA SER RELLENADO.
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complementos.
        /// </summary>
        internal static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión del producto.
        /// </summary>
        internal static string ProductVer {
            get {
                return ResourceManager.GetString("ProductVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fóndo rapido.
        /// </summary>
        internal static string QuickBackdrop {
            get {
                return ResourceManager.GetString("QuickBackdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Eventos.
        /// </summary>
        internal static string RemoveEvents {
            get {
                return ResourceManager.GetString("RemoveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Imagenes.
        /// </summary>
        internal static string RemoveImages {
            get {
                return ResourceManager.GetString("RemoveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión de tiempo de ejecución.
        /// </summary>
        internal static string RuntimeVer {
            get {
                return ResourceManager.GetString("RuntimeVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Archivo.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Juego.
        /// </summary>
        internal static string SelectGame {
            get {
                return ResourceManager.GetString("SelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establecer Iconos de Objetos.
        /// </summary>
        internal static string SetObjectIcons {
            get {
                return ResourceManager.GetString("SetObjectIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA SER RELLENADO.
        /// </summary>
        internal static string SoundInfo {
            get {
                return ResourceManager.GetString("SoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonidos.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar Sonido.
        /// </summary>
        internal static string StopSound {
            get {
                return ResourceManager.GetString("StopSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilo.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trazar trozos..
        /// </summary>
        internal static string TraceChunks {
            get {
                return ResourceManager.GetString("TraceChunks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
